import type { BirthInfo, DestinyChart } from '../core/astro/types.js';
import type { PromptContext, AIPrompt } from '../ai/promptBuilder.js';
import type { PersonalityResult } from '../ai/personality.js';
import type { CareerResult } from '../ai/career.js';
import type { RelationshipResult } from '../ai/relationship.js';
import type { StrategyResult } from '../ai/strategy.js';
import { MemoryStore } from '../memory/memoryStore.js';
import type { DashboardOptions } from '../visualization/dashboard.js';
import type { LLMClient } from './llmClient.js';
export interface AgentState {
    birth: BirthInfo;
    chart: DestinyChart;
    ctx: PromptContext;
    personality: PersonalityResult;
    career: CareerResult;
    relationship: RelationshipResult;
    strategy: StrategyResult;
    /** Memory store (optional, created on demand) */
    memory: MemoryStore | null;
    /** Conversation history */
    history: ConversationTurn[];
    /** Session metadata */
    session: SessionMeta;
}
export interface ConversationTurn {
    role: 'user' | 'agent';
    content: string;
    topic?: string;
    timestamp: string;
}
export interface SessionMeta {
    id: string;
    createdAt: string;
    lastActiveAt: string;
    turnCount: number;
}
export type QueryDomain = '性格' | '事业' | '感情' | '运势' | '战略' | '综合' | '排盘';
export interface AgentResponse {
    /** Text response */
    text: string;
    /** Whether this response was generated by an LLM */
    llmGenerated: boolean;
    /** The specific AI prompt (ready for LLM) if applicable */
    prompt?: AIPrompt;
    /** Topic extracted from query */
    topic: QueryDomain;
    /** Optional visualization */
    visualization?: string;
    /** Memory-enriched context */
    memoryContext?: string;
    /** LLM usage info */
    usage?: {
        inputTokens: number;
        outputTokens: number;
    };
}
export declare class DestinyAgent {
    state: AgentState;
    private llm;
    private deterministic;
    private llmProvider;
    constructor(birth: BirthInfo, llm?: LLMClient);
    private get providerState();
    private get toolContext();
    /**
     * Process a user query and return an agent response.
     */
    processQuery(input: string): AgentResponse;
    /**
     * Set or replace the LLM client.
     */
    setLLM(llm: LLMClient): void;
    /**
     * Check if an LLM client is configured.
     */
    hasLLM(): boolean;
    /**
     * Process a query asynchronously with LLM-generated response.
     */
    processQueryAsync(input: string): Promise<AgentResponse>;
    /**
     * Stream a query response token by token.
     */
    processQueryStream(input: string): AsyncGenerator<{
        type: 'token' | 'done' | 'error';
        content?: string;
        error?: string;
        topic?: QueryDomain;
        prompt?: AIPrompt;
    }>;
    /**
     * Build the appropriate AI prompt for a given topic.
     */
    private buildPromptForTopic;
    enableMemory(userId?: string): MemoryStore;
    loadMemory(json: string): void;
    logPredictions(): void;
    processQueryWithMemory(input: string): AgentResponse;
    renderDashboard(options?: DashboardOptions): string;
    renderChart(): string;
    getSessionSummary(): string;
}
//# sourceMappingURL=agentEngine.d.ts.map