// ============================================================
// AI Destiny OS — Astro Core: BaZi Test Suite
// Verified against known birth charts.
// ============================================================

import { describe, it, expect } from 'vitest';
import {
  calcBaZi,
  generateChart,
  formatBaZi,
  calcDaYun,
  calcLiuNian,
  getJieQi,
  sexagenaryIndex,
  stemFromSexagenary,
  branchFromSexagenary,
  getShiShen,
  getHiddenStems,
  getNayin,
  isClash,
  isCombination,
  COMBINATION_WUXING,
  getPunishment,
  isSelfPunishment,
  isHarm,
} from '../index.js';
import type { BirthInfo } from '../types.js';

// ---- Core Math Tests ----

describe('Sexagenary Cycle', () => {
  it('甲子 should be index 0', () => {
    expect(sexagenaryIndex(0, 0)).toBe(0);
  });

  it('甲戌 should be index 10', () => {
    expect(sexagenaryIndex(0, 10)).toBe(10);
  });

  it('癸亥 should be index 59', () => {
    expect(sexagenaryIndex(9, 11)).toBe(59);
  });

  it('乙丑 should be index 1', () => {
    expect(sexagenaryIndex(1, 1)).toBe(1);
  });

  it('丙寅 should be index 2', () => {
    expect(sexagenaryIndex(2, 2)).toBe(2);
  });

  it('stem and branch from index 0 → 甲子', () => {
    expect(stemFromSexagenary(0)).toBe(0);
    expect(branchFromSexagenary(0)).toBe(0);
  });

  it('stem and branch from index 59 → 癸亥', () => {
    expect(stemFromSexagenary(59)).toBe(9);
    expect(branchFromSexagenary(59)).toBe(11);
  });
});

// ---- ShiShen Tests ----

describe('ShiShen (十神)', () => {
  it('same wuxing, same yinYang → 比肩', () => {
    // 甲(阳木) vs 甲(阳木)
    expect(getShiShen(0, 0)).toBe('比肩');
  });

  it('same wuxing, diff yinYang → 劫财', () => {
    // 甲(阳木) vs 乙(阴木)
    expect(getShiShen(0, 1)).toBe('劫财');
  });

  it('dayMaster generates target, same yinYang → 食神', () => {
    // 甲(阳木) → 丙(阳火): 木生火
    expect(getShiShen(0, 2)).toBe('食神');
  });

  it('dayMaster generates target, diff yinYang → 伤官', () => {
    // 甲(阳木) → 丁(阴火): 木生火
    expect(getShiShen(0, 3)).toBe('伤官');
  });

  it('dayMaster controls target, diff yinYang → 正财', () => {
    // 甲(阳木) → 己(阴土): 木克土
    expect(getShiShen(0, 5)).toBe('正财');
  });

  it('dayMaster controls target, same yinYang → 偏财', () => {
    // 甲(阳木) → 戊(阳土): 木克土
    expect(getShiShen(0, 4)).toBe('偏财');
  });

  it('dayMaster controlled by target, diff yinYang → 正官', () => {
    // 甲(阳木) ← 辛(阴金): 金克木
    expect(getShiShen(0, 7)).toBe('正官');
  });

  it('dayMaster controlled by target, same yinYang → 七杀', () => {
    // 甲(阳木) ← 庚(阳金): 金克木
    expect(getShiShen(0, 6)).toBe('七杀');
  });

  it('dayMaster generated by target, diff yinYang → 正印', () => {
    // 甲(阳木) ← 癸(阴水): 水生木
    expect(getShiShen(0, 9)).toBe('正印');
  });

  it('dayMaster generated by target, same yinYang → 偏印', () => {
    // 甲(阳木) ← 壬(阳水): 水生木
    expect(getShiShen(0, 8)).toBe('偏印');
  });

  it('all 100 dayMaster × target combinations should return valid ShiShen', () => {
    // Complete 10×10 mapping table
    const expected: Record<number, Record<number, string>> = {
      0: { 0: '比肩', 1: '劫财', 2: '食神', 3: '伤官', 4: '偏财', 5: '正财', 6: '七杀', 7: '正官', 8: '偏印', 9: '正印' },
      1: { 0: '劫财', 1: '比肩', 2: '伤官', 3: '食神', 4: '正财', 5: '偏财', 6: '正官', 7: '七杀', 8: '正印', 9: '偏印' },
      2: { 0: '偏印', 1: '正印', 2: '比肩', 3: '劫财', 4: '食神', 5: '伤官', 6: '偏财', 7: '正财', 8: '七杀', 9: '正官' },
      3: { 0: '正印', 1: '偏印', 2: '劫财', 3: '比肩', 4: '伤官', 5: '食神', 6: '正财', 7: '偏财', 8: '正官', 9: '七杀' },
      4: { 0: '七杀', 1: '正官', 2: '偏印', 3: '正印', 4: '比肩', 5: '劫财', 6: '食神', 7: '伤官', 8: '偏财', 9: '正财' },
      5: { 0: '正官', 1: '七杀', 2: '正印', 3: '偏印', 4: '劫财', 5: '比肩', 6: '伤官', 7: '食神', 8: '正财', 9: '偏财' },
      6: { 0: '偏财', 1: '正财', 2: '七杀', 3: '正官', 4: '偏印', 5: '正印', 6: '比肩', 7: '劫财', 8: '食神', 9: '伤官' },
      7: { 0: '正财', 1: '偏财', 2: '正官', 3: '七杀', 4: '正印', 5: '偏印', 6: '劫财', 7: '比肩', 8: '伤官', 9: '食神' },
      8: { 0: '食神', 1: '伤官', 2: '偏财', 3: '正财', 4: '七杀', 5: '正官', 6: '偏印', 7: '正印', 8: '比肩', 9: '劫财' },
      9: { 0: '伤官', 1: '食神', 2: '正财', 3: '偏财', 4: '正官', 5: '七杀', 6: '正印', 7: '偏印', 8: '劫财', 9: '比肩' },
    };

    for (let dm = 0; dm < 10; dm++) {
      for (let tgt = 0; tgt < 10; tgt++) {
        const result = getShiShen(dm as HeavenlyStemIndex, tgt as HeavenlyStemIndex);
        const exp = expected[dm]![tgt];
        expect(result).toBe(exp);
      }
    }
  });

  it('all dayun pillars should have non-null shiShen', () => {
    const birth: BirthInfo = {
      year: 1993, month: 7, day: 23, hour: 9, minute: 30,
      longitude: 116.4, isDST: false, gender: '男',
    };
    const bazi = calcBaZi(birth);
    const dayun = calcDaYun(birth, bazi.month, bazi.year.stemIndex, bazi.day.stemIndex);

    for (const dy of dayun) {
      expect(dy.pillar.shiShen).toBeDefined();
      const validShiShens = ['比肩', '劫财', '食神', '伤官', '正财', '偏财', '正官', '七杀', '正印', '偏印'];
      expect(validShiShens).toContain(dy.pillar.shiShen);
    }
  });

  it('all four pillars in BaZi should have valid shiShen', () => {
    const birth: BirthInfo = {
      year: 1993, month: 7, day: 23, hour: 9, minute: 30,
      longitude: 116.4, isDST: false, gender: '男',
    };
    const bazi = calcBaZi(birth);
    const validShiShens = ['比肩', '劫财', '食神', '伤官', '正财', '偏财', '正官', '七杀', '正印', '偏印'];

    expect(validShiShens).toContain(bazi.year.shiShen);
    expect(validShiShens).toContain(bazi.month.shiShen);
    expect(bazi.day.shiShen).toBe('比肩'); // day master relative to itself
    expect(validShiShens).toContain(bazi.hour.shiShen);
  });
});

// ---- Hidden Stems Tests ----

describe('Hidden Stems (藏干)', () => {
  it('子 should contain 癸', () => {
    expect(getHiddenStems(0)).toEqual([9]); // 癸
  });

  it('寅 should contain 甲, 丙, 戊', () => {
    expect(getHiddenStems(2)).toEqual([0, 2, 4]); // 甲, 丙, 戊
  });

  it('午 should contain 丁, 己', () => {
    expect(getHiddenStems(6)).toEqual([3, 5]); // 丁, 己
  });
});

// ---- Nayin Tests ----

describe('Nayin (纳音)', () => {
  it('甲子 → 海中金', () => {
    expect(getNayin(0)).toBe('海中金');
  });

  it('丙寅 → 炉中火', () => {
    expect(getNayin(2)).toBe('炉中火');
  });
});

// ---- Known Birth Chart Tests ----

describe('BaZi Calculation — Known Charts', () => {
  /**
   * Test Case 1:
   * Birth: 1984-02-04 06:00, Beijing (116.4°E), Male
   *
   * This is an interesting case because 1984-02-04 is exactly around
   * 立春 (Start of Spring). The year pillar may be 癸亥 or 甲子
   * depending on the exact time of 立春 in 1984.
   */
  it('should calculate chart for 1984-02-04 Beijing male', () => {
    const birth: BirthInfo = {
      year: 1984,
      month: 2,
      day: 4,
      hour: 6,
      minute: 0,
      longitude: 116.4,
      isDST: false,
      gender: '男',
    };

    const bazi = calcBaZi(birth);

    // Verify structure
    expect(bazi.year).toBeDefined();
    expect(bazi.month).toBeDefined();
    expect(bazi.day).toBeDefined();
    expect(bazi.hour).toBeDefined();

    // Verify sexagenary indices are in range
    expect(bazi.year.sexagenaryIndex).toBeGreaterThanOrEqual(0);
    expect(bazi.year.sexagenaryIndex).toBeLessThan(60);
    expect(bazi.day.sexagenaryIndex).toBeGreaterThanOrEqual(0);
    expect(bazi.day.sexagenaryIndex).toBeLessThan(60);

    // Verify hidden stems are present
    expect(bazi.year.hiddenStems.length).toBeGreaterThan(0);
    expect(bazi.month.hiddenStems.length).toBeGreaterThan(0);

    // Verify nayin is a string
    expect(typeof bazi.year.nayin).toBe('string');
    expect(bazi.year.nayin.length).toBeGreaterThan(0);
  });

  /**
   * Test Case 2:
   * Birth: 1990-05-15 14:30, Shanghai (121.5°E), Female
   */
  it('should calculate chart for 1990-05-15 Shanghai female', () => {
    const birth: BirthInfo = {
      year: 1990,
      month: 5,
      day: 15,
      hour: 14,
      minute: 30,
      longitude: 121.5,
      isDST: false,
      gender: '女',
    };

    const chart = generateChart(birth);

    expect(chart.bazi).toBeDefined();
    expect(chart.dayMaster).toBeDefined();
    expect(chart.dayMasterWuxing).toBeDefined();
    expect(chart.wuxingCount).toBeDefined();
    expect(chart.dayun.length).toBeGreaterThan(0);
  });

  /**
   * Test Case 3:
   * Birth: 2000-01-01 00:30, Beijing
   * This tests the early-子时 boundary case and the year-start boundary.
   */
  it('should handle early 子时 correctly', () => {
    const birth: BirthInfo = {
      year: 2000,
      month: 1,
      day: 1,
      hour: 0,
      minute: 30,
      longitude: 116.4,
      isDST: false,
      gender: '女',
    };

    const bazi = calcBaZi(birth);

    // Early 子时 (00:00–00:59) should have hour branch 子(0)
    expect(bazi.hour.branchIndex).toBe(0);
  });

  /**
   * Test Case 4:
   * Birth with DST (夏令时)
   * China used DST from 1986-1991. Testing a DST birth.
   */
  it('should handle DST correction', () => {
    const birth: BirthInfo = {
      year: 1988,
      month: 7,
      day: 15,
      hour: 9,
      minute: 0,
      longitude: 116.4,
      isDST: true,
      gender: '男',
    };

    const bazi = calcBaZi(birth);
    expect(bazi).toBeDefined();
    // The hour pillar should reflect the time being effectively 8:00
  });
});

// ---- DaYun Tests ----

describe('DaYun (大运)', () => {
  it('should calculate dayun sequence for 甲年 male (顺排)', () => {
    const birth: BirthInfo = {
      year: 1984,  // 甲子年
      month: 6,
      day: 15,
      hour: 12,
      minute: 0,
      longitude: 116.4,
      isDST: false,
      gender: '男',
    };

    const bazi = calcBaZi(birth);
    const dayun = calcDaYun(birth, bazi.month, bazi.year.stemIndex, bazi.day.stemIndex);

    expect(dayun.length).toBe(10);
    expect(dayun[0]!.startAge).toBeGreaterThan(0);
    expect(dayun[0]!.direction).toBe('顺排');

    // Each dayun should be 10 years apart
    for (let i = 1; i < dayun.length; i++) {
      const diff = dayun[i]!.startAge - dayun[i - 1]!.startAge;
      expect(diff).toBeCloseTo(10, 0);
    }
  });

  it('should calculate dayun sequence for 甲年 female (逆排)', () => {
    const birth: BirthInfo = {
      year: 1984,  // 甲子年
      month: 6,
      day: 15,
      hour: 12,
      minute: 0,
      longitude: 116.4,
      isDST: false,
      gender: '女',
    };

    const bazi = calcBaZi(birth);
    const dayun = calcDaYun(birth, bazi.month, bazi.year.stemIndex, bazi.day.stemIndex);

    expect(dayun[0]!.direction).toBe('逆排');
  });
});

// ---- LiuNian Tests ----

describe('LiuNian (流年)', () => {
  it('should calculate annual fortunes', () => {
    const birth: BirthInfo = {
      year: 1990,
      month: 5,
      day: 15,
      hour: 14,
      minute: 0,
      longitude: 116.4,
      isDST: false,
      gender: '男',
    };

    const bazi = calcBaZi(birth);
    const liunian = calcLiuNian(bazi, 2024, 2026);

    expect(liunian.length).toBe(3);
    for (const ln of liunian) {
      expect(ln.scores.career).toBeGreaterThanOrEqual(0);
      expect(ln.scores.career).toBeLessThanOrEqual(100);
      expect(ln.scores.overall).toBeGreaterThanOrEqual(0);
      expect(ln.scores.overall).toBeLessThanOrEqual(100);
    }
  });
});

// ---- Earthly Branch Relations Tests ----

describe('Earthly Branch Relations (刑冲合害)', () => {
  describe('六冲 (Six Clashes)', () => {
    it('子午冲', () => {
      expect(isClash(0, 6)).toBe(true);
      expect(isClash(6, 0)).toBe(true);
    });
    it('丑未冲', () => { expect(isClash(1, 7)).toBe(true); });
    it('寅申冲', () => { expect(isClash(2, 8)).toBe(true); });
    it('卯酉冲', () => { expect(isClash(3, 9)).toBe(true); });
    it('辰戌冲', () => { expect(isClash(4, 10)).toBe(true); });
    it('巳亥冲', () => { expect(isClash(5, 11)).toBe(true); });
    it('non-clashing pairs should return false', () => {
      expect(isClash(0, 1)).toBe(false);
      expect(isClash(2, 3)).toBe(false);
      expect(isClash(4, 5)).toBe(false);
    });
  });

  describe('六合 (Six Combinations)', () => {
    it('子丑合土', () => { expect(isCombination(0, 1)).toBe(true); expect(isCombination(1, 0)).toBe(true); });
    it('寅亥合木', () => { expect(isCombination(2, 11)).toBe(true); });
    it('卯戌合火', () => { expect(isCombination(3, 10)).toBe(true); });
    it('辰酉合金', () => { expect(isCombination(4, 9)).toBe(true); });
    it('巳申合水', () => { expect(isCombination(5, 8)).toBe(true); });
    it('午未合土', () => { expect(isCombination(6, 7)).toBe(true); });
    it('non-combining pairs should return false', () => {
      expect(isCombination(0, 2)).toBe(false);
    });
    it('combination wuxing map should have correct elements', () => {
      expect(COMBINATION_WUXING['0,1']).toBe('土');
      expect(COMBINATION_WUXING['2,11']).toBe('木');
      expect(COMBINATION_WUXING['3,10']).toBe('火');
      expect(COMBINATION_WUXING['4,9']).toBe('金');
      expect(COMBINATION_WUXING['5,8']).toBe('水');
      expect(COMBINATION_WUXING['6,7']).toBe('土');
    });
  });

  describe('三刑 (Punishments)', () => {
    it('寅巳 → 无恩之刑', () => { expect(getPunishment(2, 5)).toBe('无恩之刑'); });
    it('巳申 → 无恩之刑', () => { expect(getPunishment(5, 8)).toBe('无恩之刑'); });
    it('寅申 → 无恩之刑', () => { expect(getPunishment(2, 8)).toBe('无恩之刑'); });
    it('丑戌 → 恃势之刑', () => { expect(getPunishment(1, 10)).toBe('恃势之刑'); });
    it('戌未 → 恃势之刑', () => { expect(getPunishment(10, 7)).toBe('恃势之刑'); });
    it('丑未 → 恃势之刑', () => { expect(getPunishment(1, 7)).toBe('恃势之刑'); });
    it('子卯 → 无礼之刑', () => { expect(getPunishment(0, 3)).toBe('无礼之刑'); });
    it('non-punishing pairs should return null', () => {
      expect(getPunishment(0, 1)).toBeNull();
      expect(getPunishment(4, 6)).toBeNull();
    });
    it('自刑 branches', () => {
      expect(isSelfPunishment(4)).toBe(true);  // 辰
      expect(isSelfPunishment(6)).toBe(true);  // 午
      expect(isSelfPunishment(9)).toBe(true);  // 酉
      expect(isSelfPunishment(11)).toBe(true); // 亥
      expect(isSelfPunishment(0)).toBe(false); // 子
      expect(isSelfPunishment(1)).toBe(false); // 丑
    });
  });

  describe('六害 (Six Harms)', () => {
    it('子未害', () => { expect(isHarm(0, 7)).toBe(true); expect(isHarm(7, 0)).toBe(true); });
    it('丑午害', () => { expect(isHarm(1, 6)).toBe(true); });
    it('寅巳害', () => { expect(isHarm(2, 5)).toBe(true); });
    it('卯辰害', () => { expect(isHarm(3, 4)).toBe(true); });
    it('申亥害', () => { expect(isHarm(8, 11)).toBe(true); });
    it('酉戌害', () => { expect(isHarm(9, 10)).toBe(true); });
    it('non-harm pairs should return false', () => {
      expect(isHarm(0, 1)).toBe(false);
    });
  });
});

// ---- JieQi Tests ----

describe('JieQi (节气)', () => {
  it('should calculate 24 solar terms', () => {
    const jieqi = getJieQi(2024);
    expect(jieqi.length).toBe(24);
  });

  it('should have 立春 around Feb 4', () => {
    const jieqi = getJieQi(2024);
    const lichun = jieqi.find(jq => jq.name === '立春');
    expect(lichun).toBeDefined();
    expect(lichun!.date.getUTCMonth()).toBe(1); // February (0-indexed)
    expect(lichun!.date.getUTCDate()).toBeGreaterThanOrEqual(3);
    expect(lichun!.date.getUTCDate()).toBeLessThanOrEqual(5);
  });

  it('should mark even indices as 节 and odd as 气', () => {
    const jieqi = getJieQi(2024);
    for (const jq of jieqi) {
      expect(jq.isJie).toBe(jq.index % 2 === 0);
    }
  });

  it('should have sequential longitudes', () => {
    const jieqi = getJieQi(2024).sort((a, b) => a.date.getTime() - b.date.getTime());
    for (let i = 1; i < jieqi.length; i++) {
      const prevLon = jieqi[i - 1]!.longitude;
      const currLon = jieqi[i]!.longitude;
      // After 冬至 (270°), next is 小寒 (285°), ..., up to 360/0
      const diff = (currLon - prevLon + 360) % 360;
      expect(diff).toBeCloseTo(15, 0);
    }
  });
});
